version: '3'

services:
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails db:create && bundle exec rails db:migrate && bundle exec rails db:seed && bundle exec rails s -b '0.0.0.0'"
    volumes:
      - ".:/smey-assignment"
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=sqlite3:db/development.sqlite3